name: nice_to_weather
description: Do You Love Sunny?.

version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  geolocator: ^9.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  fonts:
    - family: NanumSquareNeo
      fonts:
        - asset: asset/fonts/NanumSquareNeo-bRg.ttf
        - asset: asset/fonts/NanumSquareNeo-eHv.ttf
          weight: 900
        - asset: asset/fonts/NanumSquareNeo-dEb.ttf
          weight: 700
        - asset: asset/fonts/NanumSquareNeo-cBd.ttf
          weight: 500
        - asset: asset/fonts/NanumSquareNeo-aLt.ttf
          weight: 100
